[project]
name = "cecilia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "GS-Silva", email = "gabriel.ferreira.profile@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
cecilia = "cecilia:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
